### PR TITLE
Release 1.4.0

### PR DESCRIPTION
**Pull request by josteinaj**
Closes/fixes:

- #71: Print message with label of currently running scenario
- #75: Better implementation for loading files from a ZIP
- #74: Fix Travis URL

### CODE REVIEW

**Comment by bertfrees** [comment]
Thanks very much!

**Comment by josteinaj** [comment]
No problem. Sorry for not doing it before. Updating documentation on homepage now. JAR should be available on maven central already.

**Comment by josteinaj** [comment]
@bertfrees

I've checked that all the "Getting started" instructions still works, but I got an error with p:load for the maven setup. Do I need to change the POM?

https://daisy.github.io/xprocspec/

**Comment by josteinaj** [comment]
I'm testing the instructions in Docker so that I have a clean environment: `docker run --rm -it java bash`

With xproc-maven-plugin:1.0.0 and xproc-engine-calabash:1.1.0, tests starts to run but then it fails with this exception:

```
root@a27718d03751:~/my-project# mvn test
(…)
11:22:39.740 [main] DEBUG com.xmlcalabash.library.Load - Running load !1.12.1.1
11:22:39.750 [main] DEBUG com.xmlcalabash.library.Load - XProc error err:XD0011
com.xmlcalabash.core.XProcException: XProc error err:XD0011
	at com.xmlcalabash.core.XProcException.dynamicError(XProcException.java:176) ~[com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.util.XProcURIResolver.parse(XProcURIResolver.java:270) ~[com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.core.XProcRuntime.parse(XProcRuntime.java:889) ~[com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.util.DefaultXMLCalabashConfigurer.loadDocument(DefaultXMLCalabashConfigurer.java:45) ~[com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.library.Load.run(Load.java:74) ~[com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XAtomicStep.run(XAtomicStep.java:389) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XCompoundStep.run(XCompoundStep.java:262) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XTry.run(XTry.java:98) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XPipelineCall.run(XPipelineCall.java:94) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XPipeline.doRun(XPipeline.java:236) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at com.xmlcalabash.runtime.XPipeline.run(XPipeline.java:136) [com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	at org.daisy.maven.xproc.calabash.Calabash.run(Calabash.java:148) [xproc-engine-calabash-1.1.0.jar:na]
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:95) [xprocspec-runner-1.0.0.jar:na]
	at org.daisy.maven.xproc.xprocspec.XProcSpecRunner.run(XProcSpecRunner.java:168) [xprocspec-runner-1.0.0.jar:na]
	at org.daisy.maven.xproc.plugin.XProcSpecMojo.execute(XProcSpecMojo.java:122) [xproc-maven-plugin-1.0.0.jar:na]
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183) [maven-core-3.x.jar:na]
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161) [maven-core-3.x.jar:na]
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320) [maven-core-3.x.jar:na]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156) [maven-core-3.x.jar:na]
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537) [maven-embedder-3.x.jar:na]
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196) [maven-embedder-3.x.jar:na]
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141) [maven-embedder-3.x.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289) [plexus-classworlds2-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229) [plexus-classworlds2-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415) [plexus-classworlds2-2.5.2.jar:na]
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356) [plexus-classworlds2-2.5.2.jar:na]
Caused by: net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; systemId: jar:file:/root/.m2/repository/org/daisy/xprocspec/xprocspec/1.4.0/xprocspec-1.4.0.jar!/content/xml/xproc/report/; lineNumber: 1; columnNumber: 1; Premature end of file.
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:380) ~[saxon-he-9.5.1.5.jar:na]
	at com.xmlcalabash.util.XProcURIResolver.parse(XProcURIResolver.java:262) ~[com.xmlcalabash-1.1.9-p1-95.jar:1.1.9-p1-95]
	... 36 common frames omitted
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: jar:file:/root/.m2/repository/org/daisy/xprocspec/xprocspec/1.4.0/xprocspec-1.4.0.jar!/content/xml/xproc/report/; lineNumber: 1; columnNumber: 1; Premature end of file.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:420) ~[saxon-he-9.5.1.5.jar:na]
	at net.sf.saxon.event.Sender.send(Sender.java:143) ~[saxon-he-9.5.1.5.jar:na]
	at net.sf.saxon.Configuration.buildDocument(Configuration.java:3361) ~[saxon-he-9.5.1.5.jar:na]
	at net.sf.saxon.s9api.DocumentBuilder.build(DocumentBuilder.java:377) ~[saxon-he-9.5.1.5.jar:na]
	... 37 common frames omitted
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213) ~[na:1.8.0_111]
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643) ~[na:1.8.0_111]
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:396) ~[saxon-he-9.5.1.5.jar:na]
	... 40 common frames omitted
(…)
```

With xproc-maven-plugin:1.0.1 and xproc-engine-calabash:1.1.3, the tests won't run at all:

```
root@a27718d03751:~/my-project# mvn test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Hello World 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ hello-world ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ hello-world ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ hello-world ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /root/my-project/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ hello-world ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ hello-world ---
[INFO] No tests to run.
[INFO] Surefire report directory: /root/my-project/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- xproc-maven-plugin:1.0.1:xprocspec (default) @ hello-world ---
[WARNING] The POM for org.restlet.jee:org.restlet.ext.fileupload:jar:2.2.2 is missing, no dependency information available
[WARNING] The POM for org.restlet.jee:org.restlet.ext.slf4j:jar:2.2.2 is missing, no dependency information available
[WARNING] The POM for org.restlet.jee:org.restlet:jar:2.2.2 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.583s
[INFO] Finished at: Tue Aug 25 11:20:26 UTC 2020
[INFO] Final Memory: 10M/477M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.daisy.maven:xproc-maven-plugin:1.0.1:xprocspec (default) on project hello-world: Execution default of goal org.daisy.maven:xproc-maven-plugin:1.0.1:xprocspec failed: Plugin org.daisy.maven:xproc-maven-plugin:1.0.1 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.restlet.jee:org.restlet.ext.fileupload:jar:2.2.2, org.restlet.jee:org.restlet.ext.slf4j:jar:2.2.2, org.restlet.jee:org.restlet:jar:2.2.2: Failure to find org.restlet.jee:org.restlet.ext.fileupload:jar:2.2.2 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by bertfrees** [comment]
It works fine for me with xproc-maven-plugin:1.0.0 and xproc-engine-calabash:1.1.0.

**Comment by bertfrees** [comment]
The issue with xproc-engine-calabash:1.1.3 should hopefully be fixed by https://github.com/daisy/xproc-maven-plugin/commit/ccb446fd0d2c3e62e2c59fffe82e122059341d6d.

**Comment by josteinaj** [comment]
I tried again today and it still fails. Here's a docker project to demonstrate the problem (`docker build .` fails):
[xprocspec-docker-test-project.zip](https://github.com/daisy/xprocspec/files/5129192/xprocspec-docker-test-project.zip)

**Pull request merged**
